routes/web.php
<?php

use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\PlaceController;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Route::prefix('admin')->name('admin.')->group(function () {
    Route::middleware('guest')->group(function () {
        Route::get('/login', [AuthController::class, 'showLoginForm'])->name('login');
        Route::post('/login', [AuthController::class, 'authenticate']);
    });

    Route::middleware('auth')->group(function () {
        Route::post('/logout', [AuthController::class, 'logout'])->name('logout');
        Route::view('/', 'admin.index')->name('index');

        Route::get('/places', [PlaceController::class, 'index'])->name('places');
        Route::get('/places/create', [PlaceController::class, 'create'])->name('places.create');
        Route::get('/places/{id}/edit', [PlaceController::class, 'edit'])->name('places.edit');
    });
});

app/Models/Place.php
<?php

namespace App\Models;

use MongoDB\Laravel\Eloquent\Model;

class Place extends Model
{
    protected $guarded = [];
}

app/Http/Controllers/API/PlaceController.php
<?php

namespace App\Http\Controllers\API;

use App\Models\Place;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use MongoDB\BSON\Regex;
use MongoDB\Laravel\Eloquent\Builder;

class PlaceController
{
    private array $selectForLists = [
        '_id',
        'name',
        'categories',
        'thumbnail',
        'short_description',
        'location',
        'rating',
        'facilities',
    ];

    public function index(Request $request)
    {
        return Place::query()
            ->select($this->selectForLists)
            ->when($request->exists('category'), function (Builder $query) use ($request) {
                $query->where('categories', $request->get('category'));
            })
            ->when($request->exists('search'), function (Builder $query) use ($request) {
                $query->where('name', 'REGEX', new Regex($request->get('search'), 'i'));
            })
            ->simplePaginate(10);
    }

    public function show(Place $place): JsonResponse
    {
        return response()->json($place);
    }

    public function explore(Request $request): JsonResponse
    {
        $latitude = $request->query('latitude', '-6.2924303');
        $longitude = $request->query('longitude', '106.725451');
        $maxDistance = $request->query('max_distance', 1000); // in kilometers
        $facilities = $request->query('facilities', []);

        $query = Place::query()
            ->select($this->selectForLists)
            ->when($request->exists('search'), function (Builder $query) use ($request) {
                $query->where('name', 'REGEX', new Regex($request->get('search'), 'i'));
            })
            ->when($request->exists('category'), function (Builder $query) use ($request) {
                $query->where('categories', $request->get('category'));
            })
            ->when($request->exists('min_rating'), function (Builder $query) use ($request) {
                $query->where('rating', '>=', (float) $request->get('min_rating'));
            })
            ->when(count($facilities) > 0, function (Builder $query) use ($request, $facilities) {
                $query->where('facilities', ['$all' => $facilities]);
            });

        $places = $query->get();

        if ($places->isEmpty()) {
            return response()->json([]);
        }

        $scoredPlaces = $this->calculateScores($places, $latitude, $longitude, $maxDistance, $facilities);

        return response()->json($scoredPlaces);
    }

    /**
     * Decision Support System using TOPSIS
     */
    private function calculateScores($places, $latitude, $longitude, $maxDistance, $requiredFacilities): array
    {
        $weights = config('app.weights');
        $distanceArray = [];
        $ratingArray = [];
        $facilityScores = [];
        $filteredPlaces = [];

        foreach ($places as $place) {
            $distance = $this->calculateDistance($latitude, $longitude, $place->location['latitude'], $place->location['longitude']);
            if ($distance <= $maxDistance) {
                $place->distance = $distance;
                $filteredPlaces[] = $place;

                $distanceArray[] = $distance;
                $ratingArray[] = $place->rating;

                // Calculate facility score
                $facilityScore = $this->calculateFacilityScore($place->facilities, $requiredFacilities);
                $facilityScores[] = $facilityScore;
                $place->facility_score = $facilityScore;
            }
        }

        $maxRating = max($ratingArray);
        $maxDistanceScore = max($distanceArray);
        $maxFacilityScore = max($facilityScores);

        $weightedPlaces = [];
        foreach ($filteredPlaces as $place) {
            $distanceScore = $maxDistanceScore - $place->distance; // Closer distances get higher scores
            $ratingScore = $place->rating; // Higher ratings are better
            $facilityScore = $place->facility_score; // Higher facility scores are better

            $totalScore =
                ($weights['rating'] * ($ratingScore / $maxRating)) +
                ($weights['distance'] * ($distanceScore / $maxDistanceScore)) +
                ($weights['facility'] * ($facilityScore / $maxFacilityScore));

            $place->score = $totalScore;
            $weightedPlaces[] = $place;
        }

        usort($weightedPlaces, function ($a, $b) {
            return $b->score <=> $a->score;
        });

        return $weightedPlaces;
    }

    private function calculateDistance($lat1, $lon1, $lat2, $lon2): float|int
    {
        // haversine formula
        $earthRadius = 6371; // Earth radius in kilometers

        $dLat = deg2rad($lat2 - $lat1);
        $dLon = deg2rad($lon2 - $lon1);

        $a = sin($dLat / 2) * sin($dLat / 2) +
            cos(deg2rad($lat1)) * cos(deg2rad($lat2)) *
            sin($dLon / 2) * sin($dLon / 2);

        $c = 2 * atan2(sqrt($a), sqrt(1 - $a));

        return $earthRadius * $c;
    }

    private function calculateFacilityScore($placeFacilities, $requiredFacilities): float|int
    {
        if (empty($requiredFacilities)) {
            return count($placeFacilities);
        }

        $matchCount = 0;
        foreach ($requiredFacilities as $facility) {
            if (in_array($facility, $placeFacilities)) {
                $matchCount++;
            }
        }

        return $matchCount;
    }
}

app/Http/Controllers/Admin/PlaceController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Place;
use Illuminate\Contracts\View\View;

class PlaceController
{
    public function index(): View
    {
        $places = Place::paginate(15);
        return view('admin.places.index', compact('places'));
    }

    public function create(): View
    {
        return view('admin.places.form');
    }

    public function edit($id): View
    {
        $place = Place::where('_id', $id)->firstOrFail();
        return view('admin.places.form', compact('place'));
    }
}

resources/views/admin/places/form.blade.php
<x-layout>
    @if (isset($place))
        <h1>Edit {{ $place->name }}</h1>
    @else
        <h1>Add Place</h1>
    @endif
</x-layout>

resources/views/admin/places/index.blade.php
<x-layout>
    <div class="flex justify-between mb-5">
        <h1>Places</h1>
        <a href="{{ route('admin.places.create') }}" class="btn btn-primary btn-sm">+Add Place</a>
    </div>
    <div class="overflow-x-auto mt-3">
        <table class="table table-xs">
            <thead>
            <tr>
                <th>Name</th>
                <th>Category</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            @foreach($places as $place)
                <tr>
                    <td>{{ $place->name }}</td>
                    <td>{{ implode(',', $place->categories) }}</td>
                    <td class="flex gap-x-3">
                        <a href="{{ route('admin.places.edit', $place->id) }}" class="btn btn-info btn-sm">
                            <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
                                <path fill-rule="evenodd" d="M11.32 6.176H5c-1.105 0-2 .949-2 2.118v10.588C3 20.052 3.895 21 5 21h11c1.105 0 2-.948 2-2.118v-7.75l-3.914 4.144A2.46 2.46 0 0 1 12.81 16l-2.681.568c-1.75.37-3.292-1.263-2.942-3.115l.536-2.839c.097-.512.335-.983.684-1.352l2.914-3.086Z" clip-rule="evenodd"/>
                                <path fill-rule="evenodd" d="M19.846 4.318a2.148 2.148 0 0 0-.437-.692 2.014 2.014 0 0 0-.654-.463 1.92 1.92 0 0 0-1.544 0 2.014 2.014 0 0 0-.654.463l-.546.578 2.852 3.02.546-.579a2.14 2.14 0 0 0 .437-.692 2.244 2.244 0 0 0 0-1.635ZM17.45 8.721 14.597 5.7 9.82 10.76a.54.54 0 0 0-.137.27l-.536 2.84c-.07.37.239.696.588.622l2.682-.567a.492.492 0 0 0 .255-.145l4.778-5.06Z" clip-rule="evenodd"/>
                            </svg>
                        </a>
                        <button class="btn btn-warning btn-square btn-sm">
                            <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
                                <path fill-rule="evenodd" d="M8.586 2.586A2 2 0 0 1 10 2h4a2 2 0 0 1 2 2v2h3a1 1 0 1 1 0 2v12a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V8a1 1 0 0 1 0-2h3V4a2 2 0 0 1 .586-1.414ZM10 6h4V4h-4v2Zm1 4a1 1 0 1 0-2 0v8a1 1 0 1 0 2 0v-8Zm4 0a1 1 0 1 0-2 0v8a1 1 0 1 0 2 0v-8Z" clip-rule="evenodd"/>
                            </svg>
                        </button>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>

        <div class="mt-5">
            {{ $places->links('components.pagination') }}
        </div>
    </div>
</x-layout>